# Generated by Django 3.0.4 on 2020-06-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='content_date',
            field=models.DateField(auto_now=True),
        ),
    ]
